default:
  adapter: mysql2
  database: lyrical
  username: root
  password: 
  host: localhost
development:
  adapter: mysql2
  database: lyrical
  username: root
  password: 
  host: localhost
production:
  adapter: mysql2
  database: lyrical
  username: root
  password: 
  host: localhost